parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    # Factory Stripe
    App\Factory\StripePaymentIntentFactory:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'

    # Service Stripe
    App\Service\StripeService:
        arguments:
            $paymentIntentFactory: '@App\Factory\StripePaymentIntentFactory'

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'
