parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    App\Factory\StripePaymentIntentFactory: ~  # autowire et autoconfigure par défaut

    App\Service\StripeServices:
        arguments:
            $paymentIntentFactory: '@App\Factory\StripePaymentIntentFactory'

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'
